### PR TITLE
changed connect to support more options

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by essen** [comment]
Nope. Like I said the other time, we want to have a single connect option for all possible types of connections (not just host:port but also unix sockets, sqlite-like and others). We can't easily identify the connection method if you provide all this separated.

**Comment by ghost** [comment]
Hmmm, I didn't receive a notification of your comment :(

Well then I didn't understand what you meant. Can you give me a hint? Something like this:

`mysql://user:secret@localhost:3306/database?option=value&option2=value2`

**Comment by essen** [comment]
I can't give you a hint because I haven't figured it out yet. More generally I want this gist https://gist.github.com/essen/5841844 to be completed before merges start happening. It still needs return values figured out, various options, missing functions for special DB features and possibly more. There's some survey work to be done with various DBs (mysql/pgsql/sqlite/oracle/mssql/voltdb/...) to make sure the choices we make seem adequate so that we can get most of it right in one go and have few interface changes afterwards.

**Comment by essen** [comment]
Don't trash your commit though I'm sure most of it is reusable.

**Comment by ghost** [comment]
No I won't. I have some more stuff. But I want to wait until bank is more stable.

**Comment by ghost** [comment]
It's definately good to do some survey. Maybe we should have a look at stuff already out there for sql databases. Like DBI (Perl), HDBC (Haskell), JDBC (Jave), etc..

**Comment by essen** [comment]
That could also be useful.

**Comment by essen** [comment]
I suppose there's no point keeping this open. Thanks anyway. :-)

**Pull request closed without merging**
