### PR TITLE
unprepare

### PR DESCRIPTION
**Pull request by teburd**
Allows a prepare statement to be unprepared

### CODE REVIEW

**Comment by essen** [comment]
Hey, interested in merging this, but 'send_close' is probably not the best name, can you rename it to 'send_unprepare' instead? Thanks.

**Comment by teburd** [comment]
Oddly enough send_close is exactly what the MySQL docs call it, I can
change it to unprepare if thats what you'd like though

**Comment by essen** [comment]
Not surprised, mysql isn't really consistent there. Yes please rename. :)

**Comment by essen** [comment]
Merged as-is, was a better idea to be honest. Thanks!

**Pull request merged**
