### PR TITLE
Add tiny int support

### PR DESCRIPTION
**Pull request by studzien**
Add function clause for parsing tiny int.

### CODE REVIEW

**Comment by essen** [comment]
What field type does that correspond to? Thought I had all relevant ones. :)

**Comment by studzien** [comment]
Tiny int (0x01) - we're using it in our schema in several places :)
Looks like function clause for it was missing in parse_bin_row/4.
Yeah, now I see that the commit message may be a little bit confusing ;)

**Comment by essen** [comment]
No it's fine, I just never had it as a type returned by MySQL when I tested. I'll check it out, thanks!

**Comment by essen** [comment]
Merged, thanks!

**Pull request merged**
