### PR TITLE
fixes no match error in parse_handshake_init/1 

### PR DESCRIPTION
**Pull request by ghost**
This no match happens if the MySQL server doesn't send the optional auth-plugin in the initial_handshake packet. See MySQL documentation: http://dev.mysql.com/doc/internals/en/connection-phase.html#packet-Protocol::Handshake

### CODE REVIEW

**Comment by essen** [comment]
If I understand right, MySQL version before 5.5.7 didn't have auth_plugin_name, is that right?

**Comment by ghost** [comment]
Yes, that is correct. I tested against MySQL version 5.1.57-community.

**Comment by essen** [comment]
OK! Can you add a comment above the second clause saying exactly that?

**Comment by ghost** [comment]
Yes I can do that. Can you give me a hint on how to "reuse" my pull request?

**Comment by ghost** [comment]
I mean update my pull request.

**Comment by essen** [comment]
git commit --amend
git push -f ..

And it'll update automatically.

**Comment by ghost** [comment]
Okay, thanks for your help!

**Comment by essen** [comment]
Merged, thanks!

**Pull request merged**
